### PR TITLE
Update web.txt

### PR DESCRIPTION
**Pull request by StevenWilliams**
Gino does not work with sqlalchemy 1.4, throwing an error when running the alembic command. This allows the alembic command to run by forcing 1.3.
AttributeError: module 'sqlalchemy.sql.schema' has no attribute '_schema_getter'

### CODE REVIEW

**Comment by MrNaif2018** [comment]
Hi! Thank you for your PR! The thing is, gino has pinned sqlalchemy to < 1.4, so it all works. Our CI tests at the latest versions of all packages and works + the frozen versions work too
https://github.com/python-gino/gino/blob/master/pyproject.toml#L27

**Comment by StevenWilliams** [comment]
That's odd. When I installed it, it installed a later version of sqlachemy. Maybe it's just an issue with my local system or I messed up somehow?

**Comment by MrNaif2018** [comment]
What's your pip version?

**Comment by StevenWilliams** [comment]
The pip version in the venv is:
pip 20.0.2 from /home/steven/bitcart/env/lib/python3.8/site-packages/pip (python 3.8)

The one I have installed is:
pip 22.2.2 from /home/steven/.local/lib/python3.8/site-packages/pip (python 3.8)

I can't remember if I forgot to use venv or not, but those are the two I have.

**Comment by StevenWilliams** [comment]
I'm on Ubuntu 20.04 (Linux Mint 20.2).

**Comment by MrNaif2018** [comment]
```
(test) alex@PC:~/envs$ pip install gino
Collecting gino
  Using cached gino-1.0.1-py3-none-any.whl (49 kB)
Collecting SQLAlchemy<1.4,>=1.2.16
  Using cached SQLAlchemy-1.3.24-cp38-cp38-manylinux2010_x86_64.whl (1.3 MB)
```

pip 20.0.2 in venv
I guess I will close it for now, because I can't seem to have the same issue. I'm on mint 20.3
